### ISSUE TITLE
Sharing images failes with some content providers

### ISSUE THREAD

**Issue by Pixdigit** [element-hq/element-android#6377]
### Steps to reproduce

1. Where are you starting? What can you see?
I want to share an image from within an app (i.e. Firefox Klar, a browser) and share it via intent with Element.
2. What do you click?
In the share dialog I tap on the element app.

#### What did you expect?
I can share the image just as usual.
#### What happened instead?
The app crashes with missing permissions.

### Your phone model

Fairphone 3

### Operating system version

Lineage 18.1

### Application version and app store

Element 1.4.12 with OLM 3.2.11 from FDroid

### Homeserver

irrelevant

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by Pixdigit** [comment]
```
06-24 11:12:57.491 11735 11735 E AndroidRuntime: FATAL EXCEPTION: main
06-24 11:12:57.491 11735 11735 E AndroidRuntime: Process: im.vector.app, PID: 11735
06-24 11:12:57.491 11735 11735 E AndroidRuntime: java.lang.SecurityException: UID 10128 does not have permission to content://org.mozilla.klar.feature.downloads.fileprovider/mediaShareCache/278159566.jpg [user 0]
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2357)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2340)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2282)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.grantUriPermission(IActivityManager.java:6418)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.app.ContextImpl.grantUriPermission(ContextImpl.java:2056)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.content.ContextWrapper.grantUriPermission(ContextWrapper.java:856)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.content.ContextWrapper.grantUriPermission(ContextWrapper.java:856)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at im.vector.lib.multipicker.Picker.getIncomingFiles(Picker.kt:11)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at im.vector.app.features.attachments.AttachmentsHelper.handleShareIntent(AttachmentsHelper.kt:4)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at im.vector.app.features.share.IncomingShareFragment.onViewCreated(IncomingShareFragment.kt:12)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:1)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:39)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:27)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:122)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:9)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:12)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8018)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1283)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:624)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at com.android.server.uri.UriGrantsManagerService.access$1000(UriGrantsManagerService.java:117)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1440)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.grantUriPermission(ActivityManagerService.java:6516)
06-24 11:12:57.491 11735 11735 E AndroidRuntime: 
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: java.lang.SecurityException: UID 10128 does not have permission to content://org.mozilla.klar.feature.downloads.fileprovider/mediaShareCache/278159566.jpg [user 0]
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.os.Parcel.createException(Parcel.java:2357)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.os.Parcel.readException(Parcel.java:2340)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.os.Parcel.readException(Parcel.java:2282)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.IActivityManager$Stub$Proxy.grantUriPermission(IActivityManager.java:6418)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.ContextImpl.grantUriPermission(ContextImpl.java:2056)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.content.ContextWrapper.grantUriPermission(ContextWrapper.java:856)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.content.ContextWrapper.grantUriPermission(ContextWrapper.java:856)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at im.vector.lib.multipicker.Picker.getIncomingFiles(Picker.kt:11)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at im.vector.app.features.attachments.AttachmentsHelper.handleShareIntent(AttachmentsHelper.kt:4)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at im.vector.app.features.share.IncomingShareFragment.onViewCreated(IncomingShareFragment.kt:12)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:1)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:39)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:27)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:122)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:9)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:12)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.Activity.performStart(Activity.java:8018)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.os.Looper.loop(Looper.java:223)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at java.lang.reflect.Method.invoke(Native Method)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: Caused by: android.os.RemoteException: Remote stack trace:
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1283)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:624)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.server.uri.UriGrantsManagerService.access$1000(UriGrantsManagerService.java:117)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1440)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.server.am.ActivityManagerService.grantUriPermission(ActivityManagerService.java:6516)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: java.lang.SecurityException: UID 10128 does not have permission to content://org.mozilla.klar.feature.downloads.fileprovider/mediaShareCache/278159566.jpg [user 0]
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.os.Parcel.createException(Parcel.java:2357)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.os.Parcel.readException(Parcel.java:2340)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.os.Parcel.readException(Parcel.java:2282)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.IActivityManager$Stub$Proxy.grantUriPermission(IActivityManager.java:6418)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.ContextImpl.grantUriPermission(ContextImpl.java:2056)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.content.ContextWrapper.grantUriPermission(ContextWrapper.java:856)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.content.ContextWrapper.grantUriPermission(ContextWrapper.java:856)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at im.vector.lib.multipicker.Picker.getIncomingFiles(Picker.kt:11)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at im.vector.app.features.attachments.AttachmentsHelper.handleShareIntent(AttachmentsHelper.kt:4)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at im.vector.app.features.share.IncomingShareFragment.onViewCreated(IncomingShareFragment.kt:12)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:1)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:39)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:27)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:122)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:9)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:12)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.Activity.performStart(Activity.java:8018)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.os.Looper.loop(Looper.java:223)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at java.lang.reflect.Method.invoke(Native Method)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: Caused by: android.os.RemoteException: Remote stack trace:
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1283)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:624)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.server.uri.UriGrantsManagerService.access$1000(UriGrantsManagerService.java:117)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1440)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK: 	at com.android.server.am.ActivityManagerService.grantUriPermission(ActivityManagerService.java:6516)
06-24 11:12:57.507 11735 11735 E JitsiMeetSDK:
```

I do not have Jitsi Meet installed, so I presume that the SDK is used my Element Android.

**Comment by Pixdigit** [comment]
I suspect the issue lies within `https://github.com/vector-im/element-android/blob/cd72563d8b97a2cad8fb5e0fff966b84db573000/vector/src/main/java/im/vector/app/features/attachments/AttachmentsHelper.kt#L197`. It may be that it chooses the wrong type (file instead of image) but I don't have any tooling installed to debug and unfortunately don't have time to investigate further.

**Comment by RayBB** [comment]
I'm experiencing this issue consistently with Google photos, FX file browser, and I think every other app I've tried to share a file from.

**Comment by NicolasDerumigny** [comment]
I also experience the same issue on a POCO X3 Pro running MIUI 12.5.5
