### ISSUE TITLE
Cannot init sync

### ISSUE THREAD

**Issue by catfromplan9** [element-hq/element-android#7931]
### Steps to reproduce

1. Where are you starting? What can you see?
I unignored an account and clicked ok to init sync
3. What do you click?
Nothing, just open the app
3. More steps…
Sometimes after unignoring someone and doing init sync, it works, but if I've changed my account avatar prior to the last init sync it'll do this. It used to just take 10 or 15 minutes, now it is indefinite. And no, I don't have that much account data cause when I login using fresh element install it takes 5 seconds to init sync

#### What did you expect?
I expect for init sync to work like it does on first install, where everything syncs my account completely fine.
#### What happened instead?
It says loading account, that works, then it says "Loading your conversations" and gets stuck there. It does not progress no matter what I do, but it'll work fine if I reinstall and add my account again though that is a bit tedious.

### Your phone model

Pixel 5a

### Operating system version

Android 13.0

### Application version and app store

Element 1.5.18, olm 3.2.12. Google Play Store

### Homeserver

Synapse 1.74.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
We had recent issue with initial sync, but on 1.5.18 it should be fine.
When you perform a clear cache from Settings/General, do you observe the same issue?

**Comment by catfromplan9** [comment]
> 

Yes, I rebooted and restarted app too. Only fix I found was reinstall, and as I mentioned I can init sync fast after initial login so it's not a server issue

**Comment by catfromplan9** [comment]
Seems to be that it works fine until I change my avatar or display name. At that point, the next init sync will fail. It'll finish downloading the init sync data almost immediately but it'll just get stuck loading convos as I said. It could be some failure with handling the avatar or displayname change that is being processed in every room, but then I wonder why this wasn't found and patched earlier.

**Comment by drygdryg** [comment]
Have the same issue with Element Android 1.6.42. I took a closer look at the response content of `/_matrix/client/r0/sync?filter=0&set_presence=offline&timeout=0` and found that the server was inserting incorrect values in events (see `errcode` and `error`):
```json
{
    "next_batch": "s5680270_26685287_4_753634_1150132_826_1346_7412_0_1",
    "account_data": {
        "events": [
            {
                "type": "m.direct",
                "content": {
                    "errcode": "M_NOT_FOUND",
                    "error": "Account data not found",
                    "@***:matrix.***.*****": [
                        "!HeoBHytXqNISAudhlb:matrix.lds.online"
                    ],
                    "@***:matrix.***.*****"": [
                        "!gWTukmRnZguxoPeRdy:matrix.lds.online"
                    ],
                    "@***:matrix.***.*****"": [
                        "!rYUOquPWkZrfrhPEZu:matrix.lds.online"
                    ],
                    "@***:matrix.***.*****"": [
                        "!ruMkbglNytWnzrCoGu:matrix.lds.online"
                    ],
                    "@***:matrix.***.*****"": [
                        "!QLwPkAGBIVsjxEwvXu:matrix.lds.online"
                    ]
                }
            },
…
```
I ran the app in debug mode and get the following error in logcat:
```
## Sync: sync service did fail true
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
    at org.matrix.android.sdk.internal.session.sync.handler.UserAccountDataSyncHandler.handleDirectChatRooms(UserAccountDataSyncHandler.kt:175)
    at org.matrix.android.sdk.internal.session.sync.handler.UserAccountDataSyncHandler.handle(UserAccountDataSyncHandler.kt:89)
    at org.matrix.android.sdk.internal.session.sync.SyncResponseHandler.handleAccountData(SyncResponseHandler.kt:241)
    at org.matrix.android.sdk.internal.session.sync.SyncResponseHandler.access$handleAccountData(SyncResponseHandler.kt:52)
    at org.matrix.android.sdk.internal.session.sync.SyncResponseHandler$startMonarchyTransaction$2$1.invoke(SyncResponseHandler.kt:207)
    at org.matrix.android.sdk.internal.session.sync.SyncResponseHandler$startMonarchyTransaction$2$1.invoke(SyncResponseHandler.kt:204)
    at org.matrix.android.sdk.internal.database.AsyncTransactionKt$awaitTransaction$2.invokeSuspend(AsyncTransaction.kt:46)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```

**Comment by drygdryg** [comment]
Have the same issue with Element Android 1.6.42. I took a closer look at the response content of `/_matrix/client/r0/sync?filter=0&set_presence=offline&timeout=0` and found that the server was inserting incorrect values in events (see `errcode` and `error`):
```json
{
    "next_batch": "s5680270_26685287_4_753634_1150132_826_1346_7412_0_1",
    "account_data": {
        "events": [
            {
                "type": "m.direct",
                "content": {
                    "errcode": "M_NOT_FOUND",
                    "error": "Account data not found",
                    "@***:matrix.***.******": [
                        "!HeoBHytXqNISAudhlb:matrix.***.******"
                    ],
                    "@***:matrix.***.******"": [
                        "!gWTukmRnZguxoPeRdy:matrix.***.******"
                    ],
                    "@***:matrix.***.******"": [
                        "!rYUOquPWkZrfrhPEZu:matrix.***.******"
                    ],
                    "@***:matrix.***.******"": [
                        "!ruMkbglNytWnzrCoGu:matrix.***.******"
                    ],
                    "@***:matrix.***.******"": [
                        "!QLwPkAGBIVsjxEwvXu:matrix.***.******"
                    ]
                }
            },
…
```
I ran the app in debug mode and get the following error in logcat:
```
## Sync: sync service did fail true
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
    at org.matrix.android.sdk.internal.session.sync.handler.UserAccountDataSyncHandler.handleDirectChatRooms(UserAccountDataSyncHandler.kt:175)
    at org.matrix.android.sdk.internal.session.sync.handler.UserAccountDataSyncHandler.handle(UserAccountDataSyncHandler.kt:89)
    at org.matrix.android.sdk.internal.session.sync.SyncResponseHandler.handleAccountData(SyncResponseHandler.kt:241)
    at org.matrix.android.sdk.internal.session.sync.SyncResponseHandler.access$handleAccountData(SyncResponseHandler.kt:52)
    at org.matrix.android.sdk.internal.session.sync.SyncResponseHandler$startMonarchyTransaction$2$1.invoke(SyncResponseHandler.kt:207)
    at org.matrix.android.sdk.internal.session.sync.SyncResponseHandler$startMonarchyTransaction$2$1.invoke(SyncResponseHandler.kt:204)
    at org.matrix.android.sdk.internal.database.AsyncTransactionKt$awaitTransaction$2.invokeSuspend(AsyncTransaction.kt:46)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```
