### ISSUE TITLE
App does'nt start and crashes on Android 5 and 6

### ISSUE THREAD

**Issue by yostyle** [element-hq/element-android#8875]
### Steps to reproduce

1. Install Element Android 1.6.16 on Android 5 or 6
2. Launch the app

It's a regression from this PR https://github.com/element-hq/element-android/pull/8801 (cc @BillCarsonFr)

https://github.com/element-hq/element-android/blob/0a284bbeea1d9e3ac37f96acade0899ee10a0252/vector/src/main/java/im/vector/app/features/analytics/ReportedDecryptionFailurePersistence.kt#L50

```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/checkerframework/com/google/common/hash/BloomFilter;
	at im.vector.app.features.analytics.ReportedDecryptionFailurePersistence.<init>(ReportedDecryptionFailurePersistence.kt:50)
	at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl.reportedDecryptionFailurePersistence(DaggerVectorApplication_HiltComponents_SingletonC.java:9215)
	at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl.-$$Nest$mreportedDecryptionFailurePersistence(DaggerVectorApplication_HiltComponents_SingletonC.java)
	at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerVectorApplication_HiltComponents_SingletonC.java:9650)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl.injectVectorApplication2(DaggerVectorApplication_HiltComponents_SingletonC.java:9492)
	at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl.injectVectorApplication(DaggerVectorApplication_HiltComponents_SingletonC.java:9385)
	at im.vector.app.Hilt_VectorApplication.hiltInternalInject(Hilt_VectorApplication.java:52)
	at im.vector.app.Hilt_VectorApplication.onCreate(Hilt_VectorApplication.java:43)
	at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:131)
```

#### What did you expect?
The app should be started

#### What happened instead?
The app crashes.

### Operating system version

Android 5 and 6

### Application version and app store

1.6.16

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by yostyle** [comment]
For unknown reason Android Studio had replaced some imports. 

Before
```
import com.google.common.hash.BloomFilter
import com.google.common.hash.Funnels
```

After
```
import org.checkerframework.com.google.common.hash.BloomFilter
import org.checkerframework.com.google.common.hash.Funnels
```

sorry for the inconvenience
