### ISSUE TITLE
The app crashes under certain conditions.

### ISSUE THREAD

**Issue by YamatoRyou** [element-hq/element-android#8948]
### Steps to reproduce

1. Make sure the app can receive notifications and calls, and allow the app to run in the background;
2. Start the app and put it in the background;
3. Lock the screen and turn it off;
4. Use another device to call the device;
5. Observe the screen changes.

#### What did you expect?
n/a

#### What happened instead?
Although the screen shows the incoming call screen, it disappears instantly (and then automatically returns to the lock screen). Sometimes it may be displayed twice. After that, unlock the phone and enter the app, you will find that the app prompts that it has crashed. In terms of the success rate of reproduction, all the devices that can reproduce the problem here are 100%.

**This problem has appeared since the update from 1.6.22 to 1.6.24**. I tested 3 Different phones:
OnePlus MT2110 (Pixel OS, based on Android 14): Successfully reproduced the problem
Mi 9T (MIUI 12.5, based on Android 11): Successfully reproduced the problem
Nokia TA-1054 (based on Andorid 8.1): Failed to reproduce the problem, behaved normally

----
OnePlus MT2110 Tried to log out and log in again, failed to resolve the issue.
**Logs have been sent via Rageshake.**

### Your phone model

See description above.

### Operating system version

See description above.

### Application version and app store

Element Android 1.6.24

### Homeserver

Synapse 1.119.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by tsartsiom** [comment]
Confirm this bug at HONOR 200 Lite

**Comment by Alex11381** [comment]
Confirm this bug at Oneplus ACE 3

**Comment by profitrollgame** [comment]
Can confirm this: 1.6.24 on OnePlus 7T Pro with A14.

**Comment by MdotAmaan** [comment]
This has been occurring on all the devices within our org running the updated version of element. (Pixel 7a, 7 pro, 8 pro, Samsung Note 20, S21, Tab S7, Tab S8 & Tab S9). This is made even more frustrating by the fact that if a call is placed by one party while the other does the same thing, the call just keeps ringing for both until it either times out or you cut the call.

**Comment by Senliast** [comment]
I have the same problem, crashlog below.

Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: google
[Device Model]: Pixel 8
[Display]: AP2A.240905.003
[Android Version]: 14
[Android API Level]: 34
[System Locale]: de_DE
[Process ID]: 26817
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: im.vector.app
[Version Name]: 1.6.24
[Version Code]: 40106242
[Target SDK]: 34
[Min SDK]: 21
[Error Type]: JVM
[Crash Time]: 2024-12-13T19:37:51.945
[Stack Trace]:
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f3183a2 u0 im.vector.app/.features.call.audio.MicrophoneAccessService c:im.vector.app}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2243)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2214)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2520)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by ToddCrimson** [comment]
Confirmed that it is happening on version 1.6.24 from F-Droid.
App crashes when a screen locked phone is called from another phone.
Please see: https://github.com/element-hq/element-android/issues/8964

**Comment by krassle** [comment]
@bmarty 
How is this issue not already on the priority list? 
- A month since @YamatoRyou reported a detailed and 100% reproducible way to trigger it and by this time enough people mentioning a bunch of different phones affected
- The impact of it is **severe** imo, than left in crashed state there are no notifications from the app until reopened manually (for days, weeks, months, ...) 
- This is still the legacy mobile app used by the majority of people as of today, who are not yet adventurous enough to switch to the _new and almost out-of-beta_ Element X for Android

**Comment by Senliast** [comment]
Just a note from me, I tried the Element X and the calls there do either not ring at all (only notification about call arrives) or the same crash happens, i don't remember because it is a while ago. So, Element X doesn't solve this problem as well.

**Comment by rajil** [comment]
+1

**Comment by oslavq** [comment]
same here, this happens on both of my Android 15 and 13 phones
