### ISSUE TITLE
During Application Compilation -- [ksp] EpoxyProcessorException: EpoxyAttribute annotations must not be on private fields without proper getter and setter methods. (class: ValueItem, field: itemClickListener)

### ISSUE THREAD

**Issue by kayabilal4440** [element-hq/element-android#8973]
### Steps to reproduce

When I compile the 'main' and 'develop' branches, I get this error even though I haven't made any changes. I have added the build logs, exceptions and my version information below. Can you help me understand what is causing this error?

-- Exception -- 
> Task :library:external:jsonviewer:kspDebugKotlin FAILED
e: [ksp] EpoxyProcessorException: EpoxyAttribute annotations must not be on private fields without proper getter and setter methods. (class: ValueItem, field: itemClickListener)
com.airbnb.epoxy.processor.EpoxyProcessorException: EpoxyAttribute annotations must not be on private fields without proper getter and setter methods. (class: ValueItem, field: itemClickListener)
	at com.airbnb.epoxy.processor.Utils.buildEpoxyException(Utils.kt:56)
	at com.airbnb.epoxy.processor.Logger.logError(Logger.kt:61)

[Build_Logs.txt](https://github.com/user-attachments/files/18259143/Build_Logs.txt)
[Exception_Log.txt](https://github.com/user-attachments/files/18259352/Exception_Log.txt)

-- Exception image
![exception_image](https://github.com/user-attachments/assets/8ce0a150-f319-45ca-96d3-8cadcb21201b)

-- My pc versions
![pc_info_version_image](https://github.com/user-attachments/assets/4f0e9033-b9f1-4e1c-a7f4-1555b6b98a0e)
![image_version](https://github.com/user-attachments/assets/4394ee1a-6ed1-448c-9fb7-657eee325a33)

### Your phone model

Samsung A54

### Operating system version

Android 14

### Application version and app store

Element v1.6.26

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by kayabilal4440** [comment]
@onurays 
![error](https://github.com/user-attachments/assets/1f35c0c4-bb1d-46ca-9595-1a42ae1c42c4)
In my version it's public.

**Comment by onurays** [comment]
I got a fresh checkout with gradle v8.6 and it is built successfully.
