### ISSUE TITLE
Cannot login to our private local server because the app tries to connect to the public matrix server

### ISSUE THREAD

**Issue by attebjorner** [element-hq/element-android#8975]
### Steps to reproduce

1. downloaded the app
2. press "sign in"
3. I see an infinite spinner and no login form, I can't specify the address of my matrix server
4. if I wait enough I get the "network error", I assume, the app is trying to connect to the public default matrix server. 

otherwise, I have no idea why the app is compaining about network, I cannot even specify my server host

#### What did you expect?
I expect to be able to log in into my private server

#### What happened instead?
an infinite spinner, no login form

### Your phone model

Sony Xperia 10 iv, oneplus cph2415

### Operating system version

Android 12, Android 14

### Application version and app store

1.6.24, Play Store 

### Homeserver

a local Synapse server 

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by attebjorner** [comment]
I have sent you the logs right now, there is a link to the issue

**Comment by attebjorner** [comment]
the [LoginConfig](https://github.com/element-hq/element-android/blob/develop/vector/src/main/java/im/vector/app/features/login/LoginConfig.kt) doesn't seem to work, I have the latest app version from gplay, but when I try to pass my server in request params
`https://mobile.element.io?hs_url=https%3A%2F%2F2853.org&is_url=https%3A%2F%2F2853.org`
I can only see a page whick tells me I need to update my app.

**Comment by attebjorner** [comment]
also I am not sure what causing the problem with connecting to the server, as the default matrix server works fine from my network

**Comment by attebjorner** [comment]
I ran the app from the sources and see in the logs that in can actually connect to the matrix server, but after that I see the infinite spinner and nothing changes

```
2025-01-06 21:57:08.655  4150-4340  AsyncTrans...ransaction im.vector.app.debug                  V  Execute transaction in 31 millis
2025-01-06 21:57:08.714  4150-4343  FormattedJsonHttpLogger im.vector.app.debug                  V  --> GET https://matrix.org/.well-known/matrix/client
2025-01-06 21:57:09.012  4150-4343  FormattedJsonHttpLogger im.vector.app.debug                  V  <-- 200 OK https://matrix.org/.well-known/matrix/client (296ms, 420-byte body)
2025-01-06 21:57:09.029  4150-4343  FormattedJsonHttpLogger im.vector.app.debug                  V  --> GET https://matrix-client.matrix.org/_matrix/client/versions
```

**Comment by attebjorner** [comment]
I found out that the facebook is causing the issue. 

```
2025-01-06 22:01:44.164 23299-23361 fbservices:c            com.facebook.services                E  Unable to create output stream
                                                                                                    java.net.SocketException: Connection timed out
                                                                                                    	at java.net.SocketInputStream.socketRead0(Native Method)
                                                                                                    	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:173)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:143)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:985)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:949)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
                                                                                                    	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
                                                                                                    	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
                                                                                                    	at com.facebook.rti.common.a.a.c.a(AnalyticsService.java:82)
                                                                                                    	at com.facebook.rti.common.a.a.c.a(AnalyticsService.java:60)
                                                                                                    	at com.facebook.rti.common.a.a.a.a(AnalyticsHttpClient.java:46)
                                                                                                    	at com.facebook.rti.common.a.a.g$b.run(CounterAnalytics.java:143)
```
